### ISSUE TITLE
git clone dndx rpi-img-builder

### ISSUE THREAD

**Issue by D35Bonanza** [dndx/pitot#5]
git clone https://github.com/dndx/rpi-img-builder.git
does not git the pitot branch The plugin pitot is not include
~/test/rpi-img-builder/plugins$ l
dalsa        disabled       Foundation  oldstable  sshkeys  testing   wheezy
common      disableroot    fsckboot    Raspbian   stable   tmpfs     yakkety
dbreconfig  extrapackages  hostname    resizefs   stretch  Ubuntu    zesty
Debian      fake-hwclock   jessie      sid        swap     unstable
Pitot build environment. is not present

**Comment by D35Bonanza** [comment]
Configured rpi-img-builder for pitot and it fails Rpi Jessie build on usb harddisk.

No keyring installed in /home/coco/home2/test/rpi-img-builder/rootfs.base.tmp/etc/apt/trusted.gpg.d/.W: GPG error: http://archive.raspberrypi.org jessie InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/pitot/main/binary-armhf/Packages  404  Not Found [IP: 93.93.128.193 80]

With out pitot plugin rpi-img-builder builds a boot image for the testing config just adding pkgs
Builds with rpi-img-builder were successful on Debian Stretch AMD64 and Debian Rpi jessie

**Comment by D35Bonanza** [comment]
Ok almost got to build;
-- Building for version: v0.5.3-17-g18bf / 0.5git
-- Using install prefix: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/pitot/librtlsdr/build
Scanning dependencies of target rtlsdr_shared
[  3%] Building C object src/CMakeFiles/rtlsdr_shared.dir/librtlsdr.c.o
[  6%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_e4k.c.o
[ 10%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc0012.c.o
[ 13%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc0013.c.o
[ 16%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc2580.c.o
[ 20%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_r82xx.c.o
[ 23%] Linking C shared library librtlsdr.so
[ 23%] Built target rtlsdr_shared
Scanning dependencies of target convenience_static
[ 26%] Building C object src/CMakeFiles/convenience_static.dir/convenience/convenience.c.o
[ 30%] Linking C static library libconvenience_static.a
[ 30%] Built target convenience_static
Scanning dependencies of target rtl_fm
[ 33%] Building C object src/CMakeFiles/rtl_fm.dir/rtl_fm.c.o
[ 36%] Linking C executable rtl_fm
[ 36%] Built target rtl_fm
Scanning dependencies of target rtl_sdr
[ 40%] Building C object src/CMakeFiles/rtl_sdr.dir/rtl_sdr.c.o
[ 43%] Linking C executable rtl_sdr
[ 43%] Built target rtl_sdr
Scanning dependencies of target rtlsdr_static
[ 46%] Building C object src/CMakeFiles/rtlsdr_static.dir/librtlsdr.c.o
[ 50%] Building C object src/CMakeFiles/rtlsdr_static.dir/tuner_e4k.c.o
[ 53%] Building C object src/CMakeFiles/rtlsdr_static.dir/tuner_fc0012.c.o
[ 56%] Building C object src/CMakeFiles/rtlsdr_static.dir/tuner_fc0013.c.o
[ 60%] Building C object src/CMakeFiles/rtlsdr_static.dir/tuner_fc2580.c.o
[ 63%] Building C object src/CMakeFiles/rtlsdr_static.dir/tuner_r82xx.c.o
[ 66%] Linking C static library librtlsdr.a
[ 66%] Built target rtlsdr_static
Scanning dependencies of target rtl_tcp
[ 70%] Building C object src/CMakeFiles/rtl_tcp.dir/rtl_tcp.c.o
[ 73%] Linking C executable rtl_tcp
[ 73%] Built target rtl_tcp
Scanning dependencies of target rtl_test
[ 76%] Building C object src/CMakeFiles/rtl_test.dir/rtl_test.c.o
[ 80%] Linking C executable rtl_test
[ 80%] Built target rtl_test
Scanning dependencies of target rtl_adsb
[ 83%] Building C object src/CMakeFiles/rtl_adsb.dir/rtl_adsb.c.o
[ 86%] Linking C executable rtl_adsb
[ 86%] Built target rtl_adsb
Scanning dependencies of target rtl_eeprom
[ 90%] Building C object src/CMakeFiles/rtl_eeprom.dir/rtl_eeprom.c.o
[ 93%] Linking C executable rtl_eeprom
[ 93%] Built target rtl_eeprom
Scanning dependencies of target rtl_power
[ 96%] Building C object src/CMakeFiles/rtl_power.dir/rtl_power.c.o
[100%] Linking C executable rtl_power
[100%] Built target rtl_power
[ 23%] Built target rtlsdr_shared
[ 30%] Built target convenience_static
[ 36%] Built target rtl_fm
[ 43%] Built target rtl_sdr
[ 66%] Built target rtlsdr_static
[ 73%] Built target rtl_tcp
[ 80%] Built target rtl_test
[ 86%] Built target rtl_adsb
[ 93%] Built target rtl_eeprom
[100%] Built target rtl_power
Install the project...
-- Install configuration: "Release"
-- Installing: /etc/udev/rules.d/rtl-sdr.rules
-- Installing: /usr/local/lib/pkgconfig/librtlsdr.pc
-- Installing: /usr/local/include/rtl-sdr.h
-- Installing: /usr/local/include/rtl-sdr_export.h
-- Installing: /usr/local/lib/librtlsdr.so.0.5git
-- Installing: /usr/local/lib/librtlsdr.so.0
-- Installing: /usr/local/lib/librtlsdr.so
-- Installing: /usr/local/lib/librtlsdr.a
-- Installing: /usr/local/bin/rtl_sdr
-- Set runtime path of "/usr/local/bin/rtl_sdr" to ""
-- Installing: /usr/local/bin/rtl_tcp
-- Set runtime path of "/usr/local/bin/rtl_tcp" to ""
-- Installing: /usr/local/bin/rtl_test
-- Set runtime path of "/usr/local/bin/rtl_test" to ""
-- Installing: /usr/local/bin/rtl_fm
-- Set runtime path of "/usr/local/bin/rtl_fm" to ""
-- Installing: /usr/local/bin/rtl_eeprom
-- Set runtime path of "/usr/local/bin/rtl_eeprom" to ""
-- Installing: /usr/local/bin/rtl_adsb
-- Set runtime path of "/usr/local/bin/rtl_adsb" to ""
-- Installing: /usr/local/bin/rtl_power
-- Set runtime path of "/usr/local/bin/rtl_power" to ""
sh: 0: getcwd() failed: No such file or directory
Failed to set capabilities on file `/usr/local/bin/pitot' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
rootfs.mak:106: recipe for target '/root/home2/zz1/rpi-img-builder/rootfs' failed
make[1]: *** [/root/home2/zz1/rpi-img-builder/rootfs] Error 1
Makefile:21: recipe for target 'build-rootfs' failed
make: *** [build-rootfs] Error 2
Looks like some is strange Pkg-config was added to packages, in plugin pitot. postinstall fails.

**Comment by D35Bonanza** [comment]
Ok as I'm building on a xeon server/rpi disks I have to comment out plugins/pitot/postinst
# setcap CAP_SYS_TIME+ep /usr/local/bin/pitot
The build is now working.
This must before SDcard builds, I can run this after the image boots via ssh and I compile pitot. via cargo build
You can close the issue if you so wish

**Comment by dndx** [comment]
@D35Bonanza Normally I put the compiled binary to `plugins/pitot/files/usr/local/bin/pitot`, then the build script would work normally. But your method is fine as well, just need the extra step of copying after building the image.
