### ISSUE TITLE
Altitude not correct with RY385 GPS varies -1000 to 323K feet

### ISSUE THREAD

**Issue by D35Bonanza** [dndx/pitot#6]
The altitude ends up at 300K ft at times. It could be the GPS is not lockup yet after restart.
Does pitot require a Baro sensor for altitude correction ?

**Comment by dndx** [comment]
That is quite strange. I have never seen that before. Pitot uses the MSL altitude fed from the GPS, not the baro sensor.

**Comment by D35Bonanza** [comment]
Yes I know, It may be the baro sensor can be used as a cross check it, one could set it like an altimeter 
I have never seen this also, Stratux was reporting the correct altitude, it could have been the ry385, It is now normal

**Comment by dndx** [comment]
We may use the built-in baro sensor of RY83x at some point. If there is a good driver for it in Rust, that would be even better.

I did notice that during bad satellite reception, the GPS altitude varies a lot. This is normal as vertical accuracy of GPS is affected by bad signal more than horizontal.

Closing this for now, unless evidence showing bug elsewhere.
